# Generated by Django 4.1 on 2022-08-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.FloatField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_att", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contabilidade.basemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "db_table": "despesa",
            },
            bases=("contabilidade.basemodel",),
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contabilidade.basemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "db_table": "receita",
            },
            bases=("contabilidade.basemodel",),
        ),
    ]
